# AT91 Platform Support
snd-soc-at91-pcm-objs := at91-pcm.o
snd-soc-at91-ac97-objs := at91-ac97.o

obj-$(CONFIG_SND_AT91_SOC_PCM) += snd-soc-at91-pcm.o
obj-$(CONFIG_SND_AT91_SOC_AC97) += snd-soc-at91-ac97.o

# Machine support
snd-soc-at91-ac97-generic-objs := at91-ac97-generic.o

obj-$(CONFIG_SND_AT91_SOC_AC97_GENERIC) += snd-soc-at91-ac97-generic.o

